[rpc_endpoints]
eth = "${ETH_RPC_URL}"
bsc = "${BSC_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
eth = { key = "${ETH_SCAN_API_KEY}", chain = "mainnet" }
bsc = { key = "${BSC_SCAN_API_KEY}", chain = "bsc" }
base = { key = "${BASE_SCAN_API_KEY}", chain = "base" }

[profile.default]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false
src = "tsunami"
fs_permissions = [{ access = "read", path = "./" }]

[dependencies]
"@openzeppelin-contracts" = "5.2.0"
"forge-std" = "1.9.6"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
single_line_statement_blocks = "preserve"
variable_override_spacing = true
wrap_comments = false
ignore = []
