[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
eth = "https://rpc.ankr.com/eth"
bsc = "https://rpc.ankr.com/bsc"
base = "https://rpc.ankr.com/base"
polygon = "https://rpc.ankr.com/polygon"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing=false
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
single_line_statement_blocks = 'preserve'
variable_override_spacing = true
wrap_comments = false
ignore = []



