name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: SunWeb3Sec/DeFiHackLabs
          token: ${{ secrets.GITHUB_TOKEN }}
          path: upstream
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config pull.rebase false

      - name: Merge Changes
        run: |
          git pull upstream main
          git push origin main
